Set fallback value for PKG_LIBS and PKG_CPPFLAGS

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -120,16 +120,30 @@ else
     DO_UPSTREAM=
 fi
 
-echo == config PKG_LIBS and PKG_CPPFLAGS
+echo == config PKG_LIBS and PKG_CPPFLAGS for Makevars
 
 ## Running cmake --find-package under src/
 cd src
 PKG_LIBS_VALUE=`SymEngine_DIR="$SymEngine_DIR" cmake --find-package -DNAME=SymEngine -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=LINK`
+status_PKG_LIBS=$?
 PKG_CPPFLAGS_VALUE=`SymEngine_DIR="$SymEngine_DIR" cmake --find-package -DNAME=SymEngine -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=COMPILE`
+status_PKG_CPPFLAGS=$?
 cd ..
 
-echo PKG_LIBS=$PKG_LIBS_VALUE
-echo PKG_CPPFLAGS=$PKG_CPPFLAGS_VALUE
+echo set PKG_LIBS=$PKG_LIBS_VALUE
+echo set PKG_CPPFLAGS=$PKG_CPPFLAGS_VALUE
+
+if [ "$status_PKG_LIBS" -ne 0 ]; then
+    echo >&2 "generating PKG_LIBS failed with 'cmake --find-package', new reset using fallback value"
+    PKG_LIBS_VALUE="-Lupstream/symengine -lsymengine -lgmp -lmpfr"
+    echo reset PKG_LIBS=$PKG_LIBS_VALUE
+fi
+
+if [ "$status_PKG_CPPFLAGS" -ne 0 ]; then
+    echo >&2 "generating PKG_CPPFLAGS failed with 'cmake --find-package', new reset using fallback value"
+    PKG_CPPFLAGS_VALUE="-Iupstream"
+    echo reset PKG_CPPFLAGS=$PKG_CPPFLAGS_VALUE
+fi
 
 echo == generating src/Makevars
 
